# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # Uncomment this if you want to bring up
  # the  machines with a GUI
  #config.vm.provider "virtualbox" do |v|
  #  v.gui = true
  #end


  # The first machine - boxA - has a NAT device as usual and is connected to the
  # private network myNetworkA, using the IP network 192.168.50.0
  config.vm.define "boxA" do |boxA|
    boxA.vm.box = "ubuntu/bionic64"
    boxA.vm.network "private_network", ip: "192.168.50.4",
    virtualbox__intnet: "myNetworkA"
  end
  # The second machine - boxB - is connected to this network as well,
  # but has a third interface connected to a second private network
  config.vm.define "boxB" do |boxB|
    boxB.vm.box = "ubuntu/bionic64"
    boxB.vm.network "private_network", ip: "192.168.50.5",
    virtualbox__intnet: "myNetworkA"
    boxB.vm.network "private_network", ip: "192.168.60.5",
    virtualbox__intnet: "myNetworkB"
  end
  # The third machine - boxC - is connected to the second network
  config.vm.define "boxC" do |boxC|
    boxC.vm.box = "ubuntu/bionic64"
    boxC.vm.network "private_network", ip: "192.168.60.4",
    virtualbox__intnet: "myNetworkB"
  end


end
