# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # We set up one machine, with a default NAT interface and a host-only
  # interface.
  config.vm.define "boxA" do |boxA|
    boxA.vm.box = "ubuntu/bionic64"
    boxA.vm.network "private_network", ip: "192.168.50.4", :name => 'vboxnet0'
  end


end
