# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # Uncomment this if you want to bring up
  # the  machines with a GUI
  #config.vm.provider "virtualbox" do |v|
  #  v.gui = true
  #end


  # The first machine - boxA - has a NAT device as usual and, with a second device,
  # is connected to a local device
  config.vm.define "boxA" do |boxA|
    boxA.vm.hostname = "boxA"
    boxA.vm.box = "ubuntu/bionic64"
    boxA.vm.network "public_network", ip: "192.168.50.4"
  end


  # The second machine - boxB - has a NAT device as usual and, with a second device,
  # is connected to a bridge myBridge that we assume to exist and being up (!), see
  # https://github.com/hashicorp/vagrant/issues/8297
  config.vm.define "boxB" do |boxB|
    boxB.vm.hostname = "boxB"
    boxB.vm.box = "ubuntu/bionic64"
    boxB.vm.network "public_network", ip: "192.168.50.4", bridge: "myBridge"
  end

  # The third machine - boxC - is connected to the same network bridge
  config.vm.define "boxC" do |boxC|
    boxC.vm.hostname = "boxC"
    boxC.vm.box = "ubuntu/bionic64"
    boxC.vm.network "public_network", ip: "192.168.50.5", bridge: "myBridge"
  end


end
